/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yaoshun_com_AndroidTest_ndkTools */

#ifndef _Included_yaoshun_com_AndroidTest_ndkTools
#define _Included_yaoshun_com_AndroidTest_ndkTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     yaoshun_com_AndroidTest_ndkTools
 * Method:    getStringFromNDK
 * Signature: ()Ljava/lang/String;
 */
//JNIEXPORT jstring JNICALL Java_yaoshun_com_AndroidTest_ndkTools_getStringFromNDK
//  (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL
Java_yaoshun_com_AndroidTest_ndkTools_getStringFromNDK(JNIEnv *env, jclass clazz);

#ifdef __cplusplus
}
#endif
#endif

